services:
  - type: web
    name: plateforme_de_prediction_sportive_ia
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
        sync: false
    autoDeploy: true
